#!/bin/bash
: <<=cut

=head1 NAME

amavisd-agent - plugin to monitor the amavis mail filter time spend on message scanning.

=head1 APPLICABLE SYSTEMS

FIXME

=head1 CONFIGURATION

FIXME

=over 4

=item FIXME

FIXME

=back

FIXME

=head2 EXAMPLE CONFIGURATION

FIXME

=head1 INTERPRETATION

FIXME

=head1 MAGIC MARKERS

  #%# family=auto
  #%# capabilities=autoconf

=head1 VERSION

FIXME

=head1 BUGS

FIXME

=head1 AUTHOR

FIXME

=head1 LICENSE

GPLv2

=cut

AMAVISD_AGENT=${amavisdagent:=/usr/bin/amavisd-agent}

if [ "$1" = "autoconf" ]; then
        if [ -x "${AMAVISD_AGENT}" ] ; then
                echo yes
                exit 0
        else
                echo no
                exit 0
        fi
fi

if [ "$1" = "config" ]; then
    echo "graph_title Amavis mail scanning times";
    echo "graph_category amavis";
    echo "graph_vlabel Scan action times per message";
    # echo "graph_period minute";
    echo "graph_args --base 1000 -l 0";
    echo "graph_scale no";
    # echo "graph_total mails";
    ($AMAVISD_AGENT -c 1 | grep -P '^Time.*Msgs\b' | cut -b12-) | while read ACTION TIMETOTAL S TIMEMSG FOO; do
      echo "${ACTION}.label ${ACTION}";
      echo "${ACTION}.type GAUGE";
      echo "${ACTION}.min 0";
      if [[ "${ACTION}" == "Total" ]] ; then 
        echo "${ACTION}.draw LINE"
      else
        echo "${ACTION}.draw AREASTACK"
      fi;
    done
    exit 0
fi

while read ACTION TIMETOTAL S TIMEMSG FOO; do
  echo ${ACTION}.value $TIMEMSG;
done < <($AMAVISD_AGENT -c 1 | grep -P '^Time.*Msgs\b' | cut -b12-)

